config/routes.rb
Rails.application.routes.draw do
  root to: 'redirections#new'

  resources :redirections, only: [:create, :new]

  get '/:mask_url', to: 'redirections#redirect', as: :redirect
  get '/:mask_url/info', to: 'redirections#info', as: :redirection_info
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/redirection.rb
class Redirection < ApplicationRecord
  has_many :visits

  validates :url_address, presence: true, url: true
  validates :mask_url, presence: true, uniqueness: true, length: { minimum: 5, maximum: 8 }

  before_validation :set_mask_url

  private

  def set_mask_url
    self.mask_url = SecureRandom.alphanumeric(8) if mask_url.blank?
  end
end

app/models/visit.rb
class Visit < ApplicationRecord
  belongs_to :redirection
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/redirections_controller.rb
class RedirectionsController < ApplicationController
  before_action :set_redirection, only: %i[redirect info]

  def new
    @redirection = Redirection.new
  end

  def create
    @redirection = Redirection.new(redirection_params)

    if @redirection.save
      redirect_to redirection_info_path(mask_url: @redirection.mask_url), notice: 'URL has successfully been created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def redirect
    @redirection.visits.create(ip_address: request.remote_ip)
    url = @redirection.url_address
    redirect_to url.match(/https?:\/\//) ? url : "http://#{url}"
  end

  private

  def set_redirection
    @redirection = Redirection.find_by(mask_url: params[:mask_url])
    redirect_to root_path unless @redirection
  end

  def redirection_params
    params.require(:redirection).permit(:url_address, :mask_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TinyUrl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <div class="mx-5">
        <%= link_to "TinyURL", root_path, class: "navbar-brand" %>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/redirections/_form.html.erb
<div class="row">
  <% if redirection.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-info">
        <h5><%= pluralize(redirection.errors.count, "error") %> prohibited this redirection from being saved:</h5>
        <ul>
          <% redirection.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="bg-info p-5 m-3">
      <h3>Enter a long URL to make a TinyURL</h3>

      <%= form_with(model: redirection, local: true) do |form| %>
        <div class="form-group my-3">
          <%= form.label :url_address %>
          <%= form.text_field :url_address, class: 'form-control' %>
        </div>

        <div class="form-group mb-3">
          <%= form.label :mask_url, "Shorted URL (optional)" %>
          <div class="input-group">
            <span class="input-group-text">
              <%= "#{root_url}" %>
            </span>
            <%= form.text_field :mask_url, class: 'form-control' %>
          </div>

        </div>

        <div class="actions">
          <%= form.submit "Shorten URL", class: 'btn btn-success mt-2' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/redirections/info.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="bg-info p-5 m-3">
        <p>
          <strong>Url:</strong>
          <%= link_to @redirection.url_address, @redirection.url_address %>
        </p>

        <p>
          <strong>Short URL:</strong>
          <%= link_to redirect_url(@redirection.mask_url), redirect_url(@redirection.mask_url), target: "_blank" %>
        </p>

        <p>
          <strong>Visit count:</strong>
          <%= @redirection.visits.count %>
        </p>

        <%= link_to 'Shorten Another URL', root_path, class: 'btn btn-success' %>
    </div>
  </div>
</div>

app/views/redirections/new.html.erb
<div class="m-2">
  <%= render 'form', redirection: @redirection %>
</div>